In [31]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.stats.api as sms
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil

%matplotlib inline

In [51]:
def sample_size_calc_mean(control_mean,std_dev,relative_change,control_size):
    
    test_mean = control_mean*(1+(relative_change/100))
    effective_size = (test_mean - control_mean)/std_dev
    
    k=0
    
    l = [control_size,100-control_size]
    
    for i in l:

        required_n = sms.NormalIndPower().solve_power(effective_size, 
        power=0.8, 
        alpha=0.05, 
        ratio=i/(100-i),
        alternative='larger')                                                 

        required_n = ceil(required_n)
        output_mean['Change']=relative_change
        

        if k%2==0:
            output_mean.loc[len(output_mean.index)] = ['test',100-i,required_n]
        else:
            output_mean.loc[len(output_mean.index)] =['control',100-i,required_n] 

        k+=1

In [32]:
def sample_size_calc_mean(control_mean,std_dev,relative_change,control_size):
    
    test_mean = control_mean*(1+(relative_change/100))
    effective_size = (test_mean - control_mean)/std_dev
    alpha=0.05
    power=0.8
    
    required_n_test = sms.NormalIndPower().solve_power(effective_size, 
    power=0.8, 
    alpha=0.05, 
    ratio=control_size/(100-control_size),
    alternative='larger')                                                 
    required_n_test = ceil(required_n_test)
    
    required_n_control = sms.NormalIndPower().solve_power(effective_size, 
    power=0.8, 
    alpha=0.05, 
    ratio=(100-control_size)/control_size,
    alternative='larger')                                                 
    required_n_control = ceil(required_n_control)
    
    output_mean['Change']=[relative_change]
    output_mean['Split']=[str(100-control_size)+'-'+str(control_size)]
    output_mean['Test_volume']=[required_n_test]
    output_mean['Control_volume']=[required_n_control]
    output_mean['Test_mean']=[test_mean]
    output_mean['Control_mean']=[control_mean]
    output_mean['Expected STDDEV']=[std_dev]
    output_mean['Test_claims']=[ceil(required_n_test*test_mean)]
    output_mean['control_claims']=[ceil(required_n_control*control_mean)]

In [53]:
output_mean.columns

Index(['Change', 'Split', 'Test_volume', 'Control_volume', 'Test_mean',
       'Control_mean', 'Expected STDDEV', 'Test_claims', 'control_claims'],
      dtype='object')

In [47]:
final_output=pd.DataFrame()
#output_mean = pd.DataFrame()
for i in [2,5,10,25,50]:
    output_mean = pd.DataFrame()
    control_mean = 2.80
    std_dev = .66
    relative_change = 1
    control_size = i     #control percentage 
    sample_size_calc_mean(control_mean,std_dev,relative_change,control_size)
    final_output= pd.concat([final_output,output_mean])

In [48]:
final_output

,Change,Split,Test_volume,Control_volume,Test_mean,Control_mean,Expected STDDEV,Test_claims,control_claims
0,1,98-2,171756,3506,2.828,2.8,0.66,485726,9817
0,1,95-5,68703,3616,2.828,2.8,0.66,194293,10125
0,1,90-10,34352,3817,2.828,2.8,0.66,97148,10688
0,1,75-25,13741,4581,2.828,2.8,0.66,38860,12827
0,1,50-50,6871,6871,2.828,2.8,0.66,19432,19239

In [49]:
def sample_size_calc_prop(control_resp_rate,relative_change,control_size):
    
    test_resp_rate = control_resp_rate*(1+(relative_change/100))
    effect_size = sms.proportion_effectsize(control_resp_rate,test_resp_rate)  

    required_n_test = sms.NormalIndPower().solve_power(-effect_size, 
    power=0.8, 
    alpha=0.05, 
    ratio=control_size/(100-control_size),
    alternative='larger')                                                 

    required_n_test = ceil(required_n_test)

    required_n_control = sms.NormalIndPower().solve_power(-effect_size, 
    power=0.8, 
    alpha=0.05, 
    ratio=(100-control_size)/control_size,
    alternative='larger')     
    
    test_rate =control_resp_rate + (effect_size * (1 - control_resp_rate))

    output_prop['Change']=[relative_change]
    output_prop['Split']=[str(100-control_size)+'-'+str(control_size)]
    output_prop['Test_volume']=[required_n_test]
    output_prop['control_volume']=[required_n_control]
    output_prop['Test_rate']=[test_rate]
    output_prop['Control_rate']=control_resp_rate
    output_prop['Test_claims']=[ceil(required_n_test*test_rate)]
    output_prop['Control_claims']=[ceil(required_n_control*control_resp_rate)]
    output_prop['Test_LTV']=ceil(output_prop['Test_claims']*LTV)
    output_prop['Control_LTV']=ceil(output_prop['Control_claims']*LTV)

In [50]:
final_output_prop=pd.DataFrame()
for i in [2,5,10,25,50]:
    output_prop = pd.DataFrame()
    control_resp_rate = 0.552
    relative_change = 1
    control_size = i
    alpha=0.05
    power=0.8
    LTV=10
    sample_size_calc_prop(control_resp_rate,relative_change,control_size)
    final_output_prop=pd.concat([final_output_prop,output_prop])

In [51]:
final_output_prop

,Change,Split,Test_volume,control_volume,Test_rate,Control_rate,Test_claims,Control_claims,Test_LTV,Control_LTV
0,1,98-2,2505848,51139.749984,0.547024,0.552,1370760,28230,13707600,282300
0,1,95-5,1002340,52754.689457,0.547024,0.552,548305,29121,5483050,291210
0,1,90-10,501170,55685.505538,0.547024,0.552,274153,30739,2741530,307390
0,1,75-25,200468,66822.606646,0.547024,0.552,109661,36887,1096610,368870
0,1,50-50,100234,100233.909969,0.547024,0.552,54831,55330,548310,553300

In [52]:
final_output

,Change,Split,Test_volume,Control_volume,Test_mean,Control_mean,Expected STDDEV,Test_claims,control_claims
0,1,98-2,171756,3506,2.828,2.8,0.66,485726,9817
0,1,95-5,68703,3616,2.828,2.8,0.66,194293,10125
0,1,90-10,34352,3817,2.828,2.8,0.66,97148,10688
0,1,75-25,13741,4581,2.828,2.8,0.66,38860,12827
0,1,50-50,6871,6871,2.828,2.8,0.66,19432,19239

In [233]:
import numpy as np
from statsmodels.stats.power import TTestIndPower
alpha = 0.05      
ratio= [0.5, 0.4, 0.3,0.2,0.1]   #(sample size of control group and sample size of test group)
lifts= [0.04,0.05,0.06,0.07,.08,0.09]
nobs1=13000 #
final_data=pd.DataFrame()
for ratios in ratio:
    for lift in lifts:
        d = lift / np.sqrt(2)
        power_data=pd.DataFrame()
        analysis = TTestIndPower()
        calculated_power=analysis.solve_power(effect_size=d,alpha=0.05,nobs1=nobs1,ratio=ratios)
        power_data['Test/control Split']=[str(int((1-ratios)*100)) + '/' +str(int((np.round(ratios,1))*100))]
        power_data['Expected_lift']=str(int(lift*100))+'%'
        power_data['Power']=int(np.round(calculated_power*100,0))
        final_data=pd.concat([final_data,power_data])

In [235]:
final_data.pivot_table(values='Power',index='Test/control Split',columns='Expected_lift').to_excel('plotting.xlsx')